
pull_requests:
  do_not_increment_build_number: true

skip_tags: true

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - nodejs_version: 18

image:
  - Visual Studio 2022

configuration:
  - Debug

before_build:
  - nuget restore

build:
  project: Resgrid.sln

install:
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - npm config get
  - node --version
  - npm --version
  - npm install -g node-gyp
  - node-gyp -v
  - node -e "console.log(process.arch);"
  - node-gyp configure --msvs_version=2022
