version: '3.4'

services:
  resgrid.webcore:
    image: ${DOCKER_REGISTRY-}resgridwebcore
    build:
      context: .
      dockerfile: Web/Resgrid.WebCore/Dockerfile

  resgrid.web.servicescore:
    image: ${DOCKER_REGISTRY-}resgridwebservices
    build:
      context: .
      dockerfile: Web/Resgrid.Web.ServicesCore/Dockerfile

  resgrid.workers.console:
    image: ${DOCKER_REGISTRY-}resgridworkersconsole
    build:
      context: .
      dockerfile: Workers/Resgrid.Workers.Console/Dockerfile
