version: '3.9'

services:
  resgrid-web:
    image: "resgridllc/resgridwebcore"
    build:
      context: .
      dockerfile: Web/Resgrid.WebCore/Dockerfile
    ports:
      - "5151:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      - resgrid-api
      - resgrid-events
      - resgrid-db
      - resgrid-redis
      - resgrid-rabbitmq

  resgrid-api:
    image: "resgridllc/resgridwebservices"
    build:
      context: .
      dockerfile: Web/Resgrid.Web.ServicesCore/Dockerfile
    ports:
      - "5152:80"
    depends_on:
      - resgrid-events
      - resgrid-db
      - resgrid-redis
      - resgrid-rabbitmq

  resgrid-events:
    image: "resgridllc/resgridwebevents"
    build:
      context: .
      dockerfile: Web/Resgrid.Web.Eventing/Dockerfile
    ports:
      - "5153:80"
    depends_on:
      - resgrid-db
      - resgrid-redis
      - resgrid-rabbitmq

  resgrid-console:
    image: "resgridllc/resgridworkersconsole"
    container_name: worker
    build:
      context: .
      dockerfile: Workers/Resgrid.Workers.Console/Dockerfile
    depends_on:
      - resgrid-db
      - resgrid-redis
      - resgrid-rabbitmq

  resgrid-db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "5157:1433"
    build:
      context: .
      dockerfile: Data/Dockerfile

  resgrid-redis:
    image: "redis:alpine"
    command: redis-server --save 60 1 --loglevel warning
    ports:
     - "5158:6379"

  resgrid-rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=resgrid
      - RABBITMQ_DEFAULT_PASS=Resgrid321!
    ports:
      - "5160:15672"
      - "5159:5672"
