version: '3.9'

services:
  web:
    image: "resgridllc/resgridwebcore"
    ports:
      - "5151:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      - api
      - events
      - db
      - redis
      - rabbitmq

  api:
    image: "resgridllc/resgridwebservices"
    ports:
      - "5152:80"
    depends_on:
      - events
      - db
      - redis
      - rabbitmq

  events:
    image: "resgridllc/resgridwebevents"
    ports:
      - "5153:80"
    depends_on:
      - db
      - redis
      - rabbitmq

  console:
    image: "resgridllc/resgridworkersconsole"
    container_name: worker
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "5157:1433"
    build:
      context: .
      dockerfile: Data/Dockerfile

  resgrid-redis:
    image: "redis:alpine"
    command: redis-server --save 60 1 --loglevel warning
    ports:
     - "5158:6379"

  resgrid-rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=resgrid
      - RABBITMQ_DEFAULT_PASS=Resgrid321!
    ports:
      - "5160:15672"
      - "5159:5672"
